### ISSUE TITLE
Add ubuntu-ports / arm+riscv 

### ISSUE THREAD

**Issue by plumbis** [PhirePhly/micromirrors#5]
Arm and RiscV ubuntu packages/releases are hosted on http://ports.ubuntu.com/ but there are almost no mirrors carrying the arm/risc packages.

Would y'all be willing to add ubuntu-ports to your existing Ubuntu mirrors? 

Thanks for your work!

**Comment by PhirePhly** [comment]
My main concern is that we require that projects have automatic load balancers to direct clients to our mirrors and then drain our mirrors if they fail health checks. I don't get the sense that ubuntu ports even has a way to register mirrors with Canonical, let alone a mirror director. Do I have that wrong?

**Comment by plumbis** [comment]
I have no idea. I'm happy to ask around and find out but I'm not sure where to start. 

I also understand if you want to close this one out as being a PITA. I don't want to put unnecessary work on a volunteer.

**Comment by PhirePhly** [comment]
There's also the issue for apt distros in particular that the default behavior is not to use a mirror list, but to pick one mirror and hardcode it at install time, which isn't compatible with the MicroMirrors designed availability. And the ubuntu repos are huge so they don't fit on the MicroMirrors, but if the distro takes itself seriously enough that we're able to register mirror.fcix.net as a mirror that's still on the table.

**Comment by PhirePhly** [comment]
We're not interested in building our own control plane for a CDN; we're just edge capacity for existing CDNs, and APT only uses them if users deliberately points it at a `mirror://` URL. If that ever becomes default behavior for a distro we might be able to start considering hosting APT repos on MicroMirrors.
