### ISSUE TITLE
Multiple mirror servers without geolocation in Fedora Mirror Manager

### ISSUE THREAD

**Issue by ott** [PhirePhly/micromirrors#6]
The following mirrors are listed in the [Fedora Mirror Manager mirror server list](https://mirrormanager.fedoraproject.org/) but are missing from the [mirror server location list](https://mirrormanager.fedoraproject.org/map/mirrors_location.txt):

- cofractal-sea.mm.fcix.net
- mirror.fcix.net

The following mirrors are also missing from the mirror server list:

- coresite-atl.mm.fcix.net

**Comment by PhirePhly** [comment]
The lack of coresite-atl is expected; that server isn't even deployed yet.
